config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  resources :projects do
    resources :webhook_settings
  end
end

app/models/webhook_setting.rb
class WebhookSetting < ActiveRecord::Base
  unloadable
  belongs_to :project
  belongs_to :issue_query

  validate :check_url

  def check_url
    require 'uri'
    unless url =~ URI::regexp
      errors.add(:url, 'Not valid')
    end
  end
end

app/controllers/webhook_settings_controller.rb
class WebhookSettingsController < ApplicationController
  unloadable

  #before_filter :find_project, :except => [:show, :edit, :update, :destroy]
  #before_filter :authorize
  before_filter :find_project, :authorize
  before_filter :find_webhook_setting, :only=> [:edit, :show, :update, :destroy]

  def index
    @webhook_settings = WebhookSetting.where('project_id' => @project.id)
  end

  def new
  end

  def create
    @webhook_setting = WebhookSetting.new(webhook_setting_params)
    @webhook_setting.project_id = @project.id
    @webhook_setting.save
    redirect_to [@project, @webhook_setting]
  end

  def show
  end

  def edit
  end

  def update
    if @webhook_setting.update(webhook_setting_params)
      redirect_to [@project, @webhook_setting]
    else
      render 'edit'
    end
  end

  def destroy
    @webhook_setting.destroy
    redirect_to project_webhook_settings_path
  end

  private
 
  def find_project
    @project = Project.find(params[:project_id])
  rescue ActiveRecord::RecordNotFound
    render_404
  end

  def webhook_setting_params
    params.require(:webhook_setting)
    .permit(:url, :description, :post, :issue_query_id)
  end

  def find_webhook_setting
    @webhook_setting = WebhookSetting.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    render_404
  end
end

app/helpers/webhook_settings_helper.rb
module WebhookSettingsHelper
end

app/views/webhook_settings/_form.html.erb
<%= error_messages_for 'webhook_setting' %>
<p>
  <%= f.label :issue_query_id %><br>
  <% iq = IssueQuery.all.map{|i| [i.name, i.id]} %>
  <%= f.select :issue_query_id, iq  %>
</p>

<p>
  <%= f.label :url %><br>
  <%= f.text_field :url %>
</p>

<p>
  <%= f.label :description %><br>
  <%= f.text_area :description %>
</p>


<p>
  <%= f.label :post %><br>
  <%= f.check_box :post %>
</p>

<p>
  <%= f.submit %>
</p>

app/views/webhook_settings/destroy.html.erb
<h2>WebhookSettingsController#destroy</h2>

app/views/webhook_settings/edit.html.erb
<h2>Edit webhook setting</h2>

<%= form_for :webhook_setting, method: :patch,  url: project_webhook_setting_path(@project, @webhook_setting) do |f| %>
   <%= render partial: 'form', locals: {f: f}    %>
<% end %>

app/views/webhook_settings/index.html.erb
<div class="contextual">
  <%= link_to_if_authorized('new',
                            {:action => 'new', :project_id => @project},
                            :class => 'icon icon-add') %>
</div>
<h2>List of URLs webhooks</h2>
    <table class="list">
      <tr>
        <th></th>
        <th></th>
        <th></th>
        <th>URL</th>
        <th>Description</th>
      </tr>
     
      <% @webhook_settings.each do |webhook_setting| %>
        <tr>
          <td><%= link_to 'Show', project_webhook_setting_path(@project, webhook_setting) %></td>
          <td><%= link_to 'Edit', edit_project_webhook_setting_path(@project, webhook_setting) %></td>
          <td><%= link_to 'Delete', project_webhook_setting_path(@project, webhook_setting),
                  method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <td><%= webhook_setting.url %></td>
          <td><%= webhook_setting.description.slice(0, 30) %></td>
        </tr>
      <% end %>
    </table>

app/views/webhook_settings/new.html.erb
<h2>Add a new webhook URL</h2>

<%= form_for :webhook_setting, url: project_webhook_settings_path(@project) do |f| %>
    <%= render partial: 'form', locals: {f: f}    %>
<% end %>

app/views/webhook_settings/show.html.erb
<h2>Webhook Setting</h2>

    <p>
      <strong>URL:</strong>
      <%= @webhook_setting.url %>
    </p>
     
    <p>
      <strong>description:</strong>
      <%= @webhook_setting.description %>
    </p>

    <p>
      <strong>POST/GET:</strong>
      <%= @webhook_setting.post? ? 'POST' : 'GET' %>
    </p>

    <p><%= link_to 'Edit', edit_project_webhook_setting_path(@project, @webhook_setting) %></p>

    <p><%= link_to 'Back to list of webhooks', project_webhook_settings_path %></p>